package:
  version:  "{{ PROJECT_VERSION }}"
  name: 'gbasis'

source:
  path: ../../

build:
  number: 0
  script: python setup.py install

requirements:
  run:
    - python
    - numpy
    - nose
  build:
    - python
    - numpy
    - nose
    - setuptools

about:
  dev_url: https://github.com/theochem/gbasis
  description: Python library for Gaussian basis function evaluation & integrals.
  license: GNU General Public License v3 or later (GPLv3+)
  license_family: GPL3
  home: https://github.com/theochem/gbasis
  license_file: LICENSE.txt
  doc_url: https://github.com/theochem/gbasis

extra:
  recipe-maintainers: HORTON-ChemTools Dev Team <horton.chemtools@gmail.com>
