name: GBasis Build Wheels Prototype

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: cp311-manylinux_x86_64
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_ALL: >
            yum install -y cmake git &&
            git clone https://github.com/sunqm/libcint.git &&
            cd libcint &&
            mkdir build && cd build &&
            cmake -DCMAKE_INSTALL_PREFIX=/usr .. &&
            make && make install

      - uses: actions/upload-artifact@v4
        with:
          name: gbasis-wheels
          path: ./wheelhouse/*.whl