name: PyPI Release
on:
  push:
    tags:
      # Trigger on version tags (e.g., v1.0.0)
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
      # Trigger on pre-release tags (e.g., v1.0.0-alpha.1)
      - "v[0-9]+.[0-9]+.[0-9]+-*"
      - "[0-9]+.[0-9]+.[0-9]+-*"

# jobs that require additional permissions should declare them explicitly
permissions:
  contents: read

env:
  # The name of the package to be published to PyPI and TestPyPI.
  PYPI_NAME: qc-gbasis

jobs:
  build:
    name: Build distribution
    uses: ./.github/workflows/build_wheels.yaml

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs:
      - build

    runs-on: ubuntu-latest

    environment:
      name: PyPI-Release
      url: https://pypi.org/project/${{ env.PYPI_NAME }}

    # Required for PyPI Trusted Publishing.
    permissions:
      id-token: write

    steps:
      - name: Download wheels
        uses: actions/download-artifact@v8
        # download all artifacts "wheel-*" and merge them into dist/
        with:
          pattern: wheel-*
          path: dist/
          merge-multiple: true

      - name: Download source distribution
        uses: actions/download-artifact@v8
        with:
          name: sdist
          path: dist/
      - name: Show distributions to be published
        run: ls -lh dist/

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

# create github release if PyPI publish is successful
  github-release:
    name: Create GitHub Release

    needs:
      - publish-to-pypi

    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:

      # download artifacts for this runner
      - name: Download wheels
        uses: actions/download-artifact@v8
        with:
          pattern: wheel-*
          path: dist/
          merge-multiple: true

      - name: Download source distribution
        uses: actions/download-artifact@v8
        with:
          name: sdist
          path: dist/

      - name: Sign distributions with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.5.0
        with:
          # sign only files listed
          release-signing-artifacts: false
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            "${{ github.ref_name }}" \
            dist/* \
            --repo "${{ github.repository }}" \
            --verify-tag \
            --generate-notes