name: pytest

on:
  push:
    branches:
     - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  pytest:
    name: "Python ${{ matrix.py }} on OS ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    env:
      COVERAGE_SINGLE: 78
      COVERAGE_TOTAL: 78

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        py: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: "actions/checkout@v4"

      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.27'

      - name: Install old versions of supported dependencies
        if: ${{ matrix.py == '3.9'}}
        run: pip install numpy==2.0 scipy==1.13.0

      - name: Install development version (non-Windows)
        if: ${{ runner.os != 'Windows' }}
        run: |
          pip install -v -e .[dev,iodata]

      - name: Install development version (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          pip install scikit-build-core cmake ninja
          pip install --no-build-isolation -v -e .[dev,iodata]

      - name: Run Pytest
        run: |
          pip install scikit-build-core cmake ninja
          pip install --no-build-isolation -v -e .[dev,iodata]
          pytest tests/ -x --timeout=300